mule:
  p-inventory-whip:
    client_id: "passIn"
    client_secret: "passIn"
    
  p-forders-pub:
    client_id: "passIn"
    client_secret: "passIn"
    
outbound:
  host: "qa.ipaas.tfapparel.net"
  port: "443"
  maxConcurrency: "20"

  fulfillment:
    scheduler:
      frequency: "0 0/5 * 1/1 * ? *" # this will run every 5 minutes
    db:
      timeDiff: "300" #secs
      limit: "50"
    enabled: "false"

  inventory:
    scheduler:
      frequency: "0 0/2 * 1/1 * ? *" # this will run every 2 minutes
    db:
      limit: "50"
    enabled: "true"

  statusChange:
    scheduler:
      frequency: "0 0/2 * 1/1 * ? *" # this will run every 2 minutes
    db:
      limit: "50"
    enabled: "true"
  
jdbc:
  hostName: "mulesoft-integration-test.c7iscturzbsa.ap-southeast-2.rds.amazonaws.com"
  port: "3306"
  databaseName: "mulesoft-dev"
  user: "passIn"
  password: "passIn"